### ISSUE TITLE
Forum posts or GH files as "content feeders"?

### ISSUE THREAD

**Issue by StefanBrand** [WeAreFairphone/community-portal#2]
Should we, in general, use forum posts as the base for the portal's sub-pages, or rather write up the pages in `md`-files here on Github?

From my point of view, what speaks **pro forum posts**:

- Easily editable if we make them Wikis
- No new account for forum members

**Pro `md`-files** on Github:

- Easier to implement
- More emphasis on formatting (Wiki posts on the forum are often "untidy")

**Comment by Ryuno-Ki** [comment]
I see some more items here …
*Pro Markdown files`:
* Trusted source because authored manually.
* Markdown being loved by content authors, but has a certain learning curve (understanding the markup). However, there are GUis for that.
* Unique content, that is, no duplicated content warnings, because search engine crawlers discover the same contents multiple times.

*Pro forum posts*:
* Auto-updated/no need for generating content.

The more important question to me is about the purpose of this project.
I was told it should become a landing page or a portal. That is, a place which introduced a visitor about the things the community has to offer and points them to other sites for further reading.

When you start suggesting authoring/writing articles, it becomes more than that. You could have both, though. Automatically/periodically fetching content from Discourse (using a server with cron and write access to this repository) and can checkin new articles written on your own.

**Comment by Ryuno-Ki** [comment]
Missed the GitHub issue id :-/

**Comment by StefanBrand** [comment]
One example: There is this page about the EFCT18:

https://forum.fairphone.com/t/star-save-the-date-european-fairphoners-community-trip-to-amsterdam-2018-13-8-19-8-2018/32940?u=stefan

The portal should contain information about the EFCT18. So we could 

1. Pull the info from the forum
2. Simply put a link into the first post that leads to the portal (e.g. fairphone.community/efct18). That would allow us to strictly separate more-or-less static content (md on Github) and dynamic content (discussion on the forum).

*Note to myself: Have a Markdown and git workshop at EFCT18*

**Comment by StefanBrand** [comment]
As to the purpose: I'd leave everything that changes quickly on the forum. IMO the portal should not contain installation instructions for an OS, but have a link to where to find those instructions.
The info on the portal should be as "time-less" as possible and easily maintainable. 

Take the example from above again. A text for the EFCT could be like this:

> The Fairphoners from all over Europe meet up every year in Amsterdam to get to know each other, have workshops, do sightseeing and exchange knowledge about [local community events]() and the [Fairphone Angels program]().

> For the latest information about 2018's edition of the European Fairphoners Community Trip click [here]().

> Photos and reports of past events can be found here: [EFCT16]() | [EFCT17]()

The first two links would be cross-references to other portal pages and the other 3 links would be forum links.

**Comment by Ryuno-Ki** [comment]
Meh :-/

I just [signed up on Fairphone forum](https://forum.fairphone.com/u/Ryuno-Ki) to find a way to generate an API key. After some [research](https://meta.discourse.org/t/using-the-discourse-api-ruby-gem/17587) it looks like they are only for admin users :-/

So we would [need an admin](https://meta.discourse.org/t/using-the-discourse-api-ruby-gem/17587/12) to [generate a key for an user](https://meta.discourse.org/t/using-the-discourse-api-ruby-gem/17587/7), so we can use [the Gem to fetch the key](https://meta.discourse.org/t/using-the-discourse-api-ruby-gem/17587/12) (means: No need to send the credential to somebody as far as I understand).

I am looking into, whether I can use RSS feeds instead.

**Comment by StefanBrand** [comment]
You can append ".json" to any topic link (instead of ".html") and it will get you the topic as a json-file.
-- 
Diese Nachricht wurde von meinem Fairphone mit K-9 Mail gesendet.

Am 30. November 2017 21:44:36 MEZ schrieb "André Jaenisch" <notifications@github.com>:
>Meh :-/
>
>I just [signed up on Fairphone
>forum](https://forum.fairphone.com/u/Ryuno-Ki) to find a way to
>generate an API key. After some
>[research](https://meta.discourse.org/t/using-the-discourse-api-ruby-gem/17587)
>it looks like they are only for admin users :-/
>
>So we would [need an
>admin](https://meta.discourse.org/t/using-the-discourse-api-ruby-gem/17587/12)
>to [generate a key for an
>user](https://meta.discourse.org/t/using-the-discourse-api-ruby-gem/17587/7),
>so we can use [the Gem to fetch the
>key](https://meta.discourse.org/t/using-the-discourse-api-ruby-gem/17587/12)
>(means: No need to send the credential to somebody as far as I
>understand).
>
>I am looking into, whether I can use RSS feeds instead.

**Comment by Ryuno-Ki** [comment]
Woah, that works! Great!

Hacking on it now :)

**Comment by Ryuno-Ki** [comment]
It looks like this:

![article-with-forum-link](https://user-images.githubusercontent.com/3097194/33458471-a01d12a4-d626-11e7-9dd1-5faff694d41b.png)

The build times are horrible, but hey, it renders a static site, so that should be negligible. Opinions?

**Comment by StefanBrand** [comment]
I like the "Further Reading" part. Maybe it can have a "fade-out-effect" like with a paywall and a link that directly leads to the forum (of course without fees! 😄 ).

**Comment by Ryuno-Ki** [comment]
Do you want to have the Fairphone brand associated with paywalls?

We could deemphasize it, if you want. On the other hand, the purpose of the portal is to lead visitors to the forum … I wouldn't include anything that impedes that.

**Comment by StefanBrand** [comment]
Yeah, but if people can read everything on the portal, why should they visit the forum? 

That's a UX question and I'm probably not the best one to ask, so don't weigh my opinion too high! 😅
-- 
Diese Nachricht wurde von meinem Fairphone mit K-9 Mail gesendet.

Am 3. Dezember 2017 21:48:24 MEZ schrieb "André Jaenisch" <notifications@github.com>:
>Do you want to have the Fairphone brand associated with paywalls?
>
>We could deemphasize it, if you want. On the other hand, the purpose of
>the portal is to lead visitors to the forum … I wouldn't include
>anything that impedes that.
