### ISSUE TITLE
The Fairphone colour guide

### ISSUE THREAD

**Issue by StefanBrand** [WeAreFairphone/community-portal#4]
![fairphone_color_guide_new](https://user-images.githubusercontent.com/8948865/33342931-f1745562-d483-11e7-9e79-48b5e5be1ca1.jpg)

**Comment by Ryuno-Ki** [comment]
![screenshot_20171128-214139](https://user-images.githubusercontent.com/3097194/33344248-9ea7b1d0-d488-11e7-89e8-74bc15943c9a.png)

I can extract the values using a colour picker later.

Dominant colour should be „Fairphone blue“. Other muted colours like here are fine, too. More information will be released later this week.

**Comment by StefanBrand** [comment]
See #14
