### ISSUE TITLE
Turn TODO section into GitHub issues

### ISSUE THREAD

**Issue by Ryuno-Ki** [WeAreFairphone/community-portal#7]
Ideally my brainstorm approach should be turned into proper GitHub issues, so people could take over some parts. Anybody have time to create a ticket for each unchecked item in the TODO section of README?

**Comment by esquith** [comment]
I could do it, please let me know if I can

**Comment by Ryuno-Ki** [comment]
Sure, go ahead :-)

I can't assign you on GitHub, since you are not a member.
Since I will be de facto offline between Christmas and New Year, I can't lend you a hand in that time. Feel free to ask anyway and I come back to you early next year :-)

**Comment by esquith** [comment]
No idea how to become a member. As far as the rest of that, sounds good.

**Comment by esquith** [comment]
Alright, I made them

**Comment by Ryuno-Ki** [comment]
I'm back, so feel free to reach out to me for feedback/review request.

**Comment by Ryuno-Ki** [comment]
Wow, nice work, @esquith!
One last thing: Can you click on the pen button in [README.md](https://github.com/WeAreFairphone/community-portal/blob/5dee810c0eaa1751c711cfcdc3ade11a38640f28/README.md) (next to the trash can) and remove the TODO items? You can enter a commit message to complete the job.

**Comment by Ryuno-Ki** [comment]
Alright, thanks for your help @esquith! I am closing this issue since everything was done.
